export {
  FORM_COMPACT_FIELD_CLASS as TRANSACTION_COMPACT_FIELD_CLASS,
  FORM_COMPACT_MOBILE_NUMERIC_INPUT_CLASS as TRANSACTION_COMPACT_MOBILE_NUMERIC_INPUT_CLASS,
  FORM_COMPACT_MOBILE_NUMERIC_VALUE_CLASS as TRANSACTION_COMPACT_MOBILE_NUMERIC_VALUE_CLASS,
  FORM_COMPACT_LABEL_CLASS as TRANSACTION_COMPACT_LABEL_CLASS,
  FORM_COMPACT_LABEL_ROW_CLASS as TRANSACTION_COMPACT_LABEL_ROW_CLASS,
  FORM_COMPACT_LABEL_INLINE_CLASS as TRANSACTION_COMPACT_LABEL_INLINE_CLASS,
  FORM_CARD_CLASS as TRANSACTION_FORM_CARD_CLASS,
} from '../form-shell/form-field.constants';
